### ISSUE TITLE
二维码识别失败

### ISSUE THREAD

**Issue by gandli** [STranslate/STranslate#105]
试了一下草料生成的二维码，识别不来。

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/c0f44c40-a822-441b-8942-b32bea78b7f6)

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/fda35102-8d73-48f5-8968-159f513a9b95)

**Comment by ZGGSONG** [comment]
二维码识别是离线的，不需要联网
