### ISSUE TITLE
自动发音和生词本

### ISSUE THREAD

**Issue by gbsix** [STranslate/STranslate#136]
沙拉很久不更新了，偶然发现这个软件，很不错。希望可以借鉴更多其他优秀的功能，比如查词自动发音功能，添加生词本功能（像沙拉那样带上来源-上下文内容），便于导出和导入。历史记录并不能替代生词本。感谢大佬！

**Comment by ZGGSONG** [comment]
这个个我看下有没有必要加吧

**Comment by jiabaoyu** [comment]
同希望有生词本功能

**Comment by uctdsb** [comment]
> 这个个我看下有没有必要加吧
那, 能否增加一个发音的快捷键?  
我倒也不需要自动发音, 但有时候有些单词我知道它的意思, 但是念的不熟, 想确认一下它的发音.
所以能否这样, 
当我高亮选中或者"ctrl+c"一个英文单词或者句子, 按下快捷键, 它可以调用TTS, 对其朗读.
