### ISSUE TITLE
智谱AI 可否增加使用 token的方式 调用，类似 openai-translator 的实现效果

### ISSUE THREAD

**Issue by 1984anonymous** [STranslate/STranslate#243]
**Describe the pain point and your solution**
  API 收费

**Describe alternatives you've tried or considered**
 参考链接： https://github.com/openai-translator/openai-translator/blob/main/docs/chatglm-cn.md

**Screenshots or sketches**

**Comment by hezhizheng** [comment]
https://github.com/LLM-Red-Team/glm-free-api  +自定义 open ai 的接口 可以满足这个功能 
key 就填  chatglm_refresh_token
![image](https://github.com/user-attachments/assets/8ac0113e-70c4-4f0b-adbf-31aa8744402c)
